# MARK: ruff
[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF"]
# E402: Ignore module level import not at top of file
ignore = ["E402"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

# MARK: black
[tool.black]
line-length = 120
